import {createClient} from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL||'';const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';export const cloud=url&&key?createClient(url,key):null;export const cloudReady=!!cloud;
export async function logActivity(action:string,entity_type:string,details:any={},source_type='manual',source_ref=''){if(!cloud)return;await cloud.from('activity_log').insert({action,entity_type,details,source_type,source_ref});}
export async function getActivities(){if(!cloud)return[];const{data,error}=await cloud.from('activity_log').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
export async function deleteActivity(id:string){if(!cloud)throw new Error('Supabase not configured');const{data:r,error:readError}=await cloud.from('activity_log').select('*').eq('id',id).single();if(readError)throw readError;if(r?.source_ref){if(r.entity_type==='semester_snapshot'){const{error}=await cloud.from('semester_snapshots').delete().eq('id',r.source_ref);if(error)throw error;}else if(r.entity_type==='document'){const{error}=await cloud.from('documents').delete().eq('id',r.source_ref);if(error)throw error;await deleteLocalFile(r.source_ref).catch(()=>{});}else if(r.entity_type==='mark'){const{error}=await cloud.from('marks').delete().eq('id',r.source_ref);if(error)throw error;}else if(r.entity_type==='import'){const ids=(r.details?.mark_ids||[]) as string[];if(ids.length){const{error}=await cloud.from('marks').delete().in('id',ids);if(error)throw error;}const{error}=await cloud.from('imports').delete().eq('id',r.source_ref);if(error)throw error;await deleteLocalFile('import-'+r.source_ref).catch(()=>{});}}const{error}=await cloud.from('activity_log').delete().eq('id',id);if(error)throw error;window.dispatchEvent(new Event('gradeflow-data-changed'));window.dispatchEvent(new Event('gradeflow-marks-changed'));}
export async function clearActivities(){if(!cloud)throw new Error('Supabase not configured');const rows=await getActivities();for(const r of rows)await deleteActivity(r.id);}
export async function getMarks(limit=20){if(!cloud)return[];const{data,error}=await cloud.from('marks').select('*').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return(data||[]).map((x:any)=>({...x,score:Number(x.score),max:Number(x.max)}));}
export async function addMark(v:any){if(!cloud)throw new Error('Supabase not configured');const payload={...v,date:v.date||new Date().toLocaleDateString('en-IN')};const{data,error}=await cloud.from('marks').insert(payload).select().single();if(error)throw error;await logActivity('Mark added','mark',{sem:data.sem,sub:data.sub,type:data.type,score:data.score,max:data.max},'academic-hub',data.id);window.dispatchEvent(new Event('gradeflow-marks-changed'));return{...data,score:Number(data.score),max:Number(data.max)};}
export async function updateMark(id:string,v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('marks').update(v).eq('id',id).select().single();if(error)throw error;await logActivity('Mark corrected','mark',{sem:data.sem,sub:data.sub,type:data.type,score:data.score,max:data.max},'academic-hub',id);window.dispatchEvent(new Event('gradeflow-marks-changed'));return{...data,score:Number(data.score),max:Number(data.max)};}
export async function getDocuments(){if(!cloud)return[];const{data,error}=await cloud.from('documents').select('*').order('pinned',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function addDocumentMeta(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('documents').insert(v).select().single();if(error)throw error;await logActivity('Document uploaded','document',{name:v.name,category:v.category,semester:v.semester,size:v.metadata?.size},'device',data.id);return data;}
export async function deleteDocument(id:string,name:string){if(!cloud)throw new Error('Supabase not configured');const{error}=await cloud.from('documents').delete().eq('id',id);if(error)throw error;await deleteLocalFile(id);await logActivity('Document deleted','document',{name},'device',id);}
export async function getSnapshots(){if(!cloud)return[];const{data,error}=await cloud.from('semester_snapshots').select('*').order('semester',{ascending:false});if(error)throw error;return data||[];}
export async function saveSnapshot(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('semester_snapshots').upsert(v,{onConflict:'semester'}).select().single();if(error)throw error;await logActivity('Semester snapshot saved','semester_snapshot',{semester:v.semester,predicted_sgpa:v.predicted_sgpa,actual_sgpa:v.actual_sgpa},'gradeflow',data.id);window.dispatchEvent(new Event('gradeflow-data-changed'));return data;}
export async function deleteSnapshot(id:string,semester:number){if(!cloud)throw new Error('Supabase not configured');const{error}=await cloud.from('semester_snapshots').delete().eq('id',id);if(error)throw error;await cloud.from('activity_log').delete().eq('entity_type','semester_snapshot').eq('source_ref',id);window.dispatchEvent(new Event('gradeflow-data-changed'));}
export async function createImport(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('imports').insert(v).select().single();if(error)throw error;await logActivity('Academic import received','import',{file_name:v.file_name,status:v.status},v.source_type||'manual',data.id);return data;}
export async function applyImport(importId:string,changes:any[],fileName='AI import'){if(!cloud)throw new Error('Supabase not configured');const applied:any[]=[];for(const c of changes){if(c.type!=='mark'||c.value==null||c.max==null)continue;const sem=Number(c.semester||3);const sub=String(c.subject_code||c.subject||'').trim();if(!sub)continue;const payload={sem,sub,type:String(c.assessment||'Other'),score:Number(c.value),max:Number(c.max),date:new Date().toLocaleDateString('en-IN')};const{data,error}=await cloud.from('marks').insert(payload).select().single();if(error)throw error;applied.push({...data,score:Number(data.score),max:Number(data.max)});}await cloud.from('imports').update({status:'applied'}).eq('id',importId);await logActivity('AI import applied','import',{file_name:fileName,mark_ids:applied.map(x=>x.id),changes:applied},'gemini',importId);window.dispatchEvent(new Event('gradeflow-marks-changed'));return applied;}
export async function undoImport(importId:string){if(!cloud)throw new Error('Supabase not configured');const{data:logs,error}=await cloud.from('activity_log').select('*').eq('action','AI import applied').eq('source_ref',importId).order('created_at',{ascending:false}).limit(1);if(error)throw error;const ids=(logs?.[0]?.details?.mark_ids||[]) as string[];if(ids.length){const{error:delError}=await cloud.from('marks').delete().in('id',ids);if(delError)throw delError;}await cloud.from('imports').update({status:'undone'}).eq('id',importId);await logActivity('AI import undone','import',{removed_mark_ids:ids},'gemini',importId);window.dispatchEvent(new Event('gradeflow-marks-changed'));return ids;}
export async function saveRule(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('assessment_rules').insert(v).select().single();if(error)throw error;await logActivity('Assessment rule added','assessment_rule',v,'import',data.id);return data;}
function db(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('gradeflow-vault',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
export async function saveLocalFile(id:string,file:File){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(file,id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
export async function getLocalFile(id:string){const d=await db();return new Promise<File|null>((ok,no)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
export async function deleteLocalFile(id:string){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').delete(id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
