import {createClient} from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL||'';const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';export const cloud=url&&key?createClient(url,key):null;export const cloudReady=!!cloud;
export async function logActivity(action:string,entity_type:string,details:any={},source_type='manual',source_ref=''){if(!cloud)return;await cloud.from('activity_log').insert({action,entity_type,details,source_type,source_ref});}
export async function getActivities(){if(!cloud)return[];const{data,error}=await cloud.from('activity_log').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
export async function getDocuments(){if(!cloud)return[];const{data,error}=await cloud.from('documents').select('*').order('pinned',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function addDocumentMeta(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('documents').insert(v).select().single();if(error)throw error;await logActivity('Document uploaded','document',{name:v.name,category:v.category,semester:v.semester,size:v.metadata?.size},'device',data.id);return data;}
export async function deleteDocument(id:string,name:string){if(!cloud)throw new Error('Supabase not configured');const{error}=await cloud.from('documents').delete().eq('id',id);if(error)throw error;await deleteLocalFile(id);await logActivity('Document deleted','document',{name},'device',id);}
export async function getSnapshots(){if(!cloud)return[];const{data,error}=await cloud.from('semester_snapshots').select('*').order('semester',{ascending:false});if(error)throw error;return data||[];}
export async function saveSnapshot(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('semester_snapshots').upsert(v,{onConflict:'semester'}).select().single();if(error)throw error;await logActivity('Semester snapshot saved','semester_snapshot',{semester:v.semester,predicted_sgpa:v.predicted_sgpa,actual_sgpa:v.actual_sgpa},'gradeflow',data.id);return data;}
export async function createImport(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('imports').insert(v).select().single();if(error)throw error;await logActivity('Academic import received','import',{file_name:v.file_name,status:v.status},v.source_type||'manual',data.id);return data;}
export async function saveRule(v:any){if(!cloud)throw new Error('Supabase not configured');const{data,error}=await cloud.from('assessment_rules').insert(v).select().single();if(error)throw error;await logActivity('Assessment rule added','assessment_rule',v,'import',data.id);return data;}
function db(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open('gradeflow-vault',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
export async function saveLocalFile(id:string,file:File){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put(file,id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
export async function getLocalFile(id:string){const d=await db();return new Promise<File|null>((ok,no)=>{const r=d.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
export async function deleteLocalFile(id:string){const d=await db();return new Promise<void>((ok,no)=>{const t=d.transaction('files','readwrite');t.objectStore('files').delete(id);t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
